### ISSUE TITLE
Font in tabs unchangable

### ISSUE THREAD

**Issue by zerocool947** [guari/eclipse-ui-theme#16]
I love the theme! I have no idea how to send a message through github, but I wanted to request a modification (or maybe even a rebuilt jar) for a slightly more... standard tab font. I'm talking about this: 

![image](https://f.cloud.github.com/assets/5566705/1709988/3624f0fa-6128-11e3-8c4a-cc0e80853f12.png)

The italics/cursive font just doesn't look good and the plugin comes in a jar, so I can't modify the CSS myself. Is there something that can be done about this?

**Comment by jcogilvie** [comment]
+1 to this.  I can't change it from the eclipse dialog for part title fonts.

**Comment by guari** [comment]
To change it you need to open the jar with an archive manager and modify the value of the `font-family` properties into `/themes/css/moonrise-ui-standalone.css`.
Since it seems that there are many users that prefer the 'standard' font for the tabs title, I will set it as default in the next version.

The possibility to change font styles and colors from the Settings dialog instead should be available starting from Eclipse 4.4 final release.
