### ISSUE TITLE
Theme does not look like promoted under Kepler

### ISSUE THREAD

**Issue by lschuetze** [guari/eclipse-ui-theme#33]
Hello,

I am using Ubuntu 13.10 and Eclipse Kepler SR1. The theme (MoonRise) does not look like yours (see picture below). The colors for the line numbers is changeable.  Even if I follow your complete "how to" it will not look like yours.

![image](https://f.cloud.github.com/assets/2911272/1931752/1fd05264-7ec3-11e3-983a-7c67629e322b.png)

What did you apply what is not in the "how to"?
Thanks in advance.

**Comment by guari** [comment]
Hi, what do you mean for 'The colors for the line numbers is changeable'? I can't see nothing wrong in your screenshot. 

For code editor colors, have you imported the .epf file for syntax highlighting?

**Comment by lschuetze** [comment]
Hi,
I mean the background color for the line numbers from the editor is changeable (in standard it is white). Importing the .epf files already changes this to the right background color.

As you can see the header of the problems dialog are not themed right. However, they are in your provided picture. Second, the color of a marked item in the outline view is different here from yours. I did not provide a screenshot for this, yet. Furthermore your fonts look totally different from mine even when providing 'Open Sans' as font, which should look similar to the one you mentioned.

**Comment by guari** [comment]
ok, the background color for line numbers suffers of an Eclipse bug, it does not follow the whole editor CSS styles and it ignores focus state, it's forced by the Eclipse platform to the color you set in Preferences (with the .epf file provided your preferences for syntax highlight are overriden).
For the rest, it's all written in the readme. The headers of the tables cannot be styled because are forced by SWT to inherit your system widget theme, same goes for the marked item in Outline (or any other Views).
The font of the title of the tabs in the screenshot is 'Segoe Print', you have to change it by editing moonrise plugin CSS for now.

**Comment by lschuetze** [comment]
Ok, thank you. Thought the table headers are themeable, too. The font isnt provided in the Eclipse used for the screenshot. Nevertheless, thank you.

**Comment by guari** [comment]
'Segoe Print' font used in the screenshot is a closed font (it's made by Microsoft), so I can't write a direct link to download (anyway you can google for it or import from a Windows platform if you like ;)). The others fonts used in the Ubuntu screenshot are the default ones for that platform ('Ubuntu' for GUI and 'Ubuntu Mono' for code)
