### ISSUE TITLE
Not working on ADT Bundle for Android development

### ISSUE THREAD

**Issue by danigonlinea** [guari/eclipse-ui-theme#35]
I could added on plugins but when I configured it on ADT Bundle, the result was really horrible. Why? Deeply, it is Eclipse.

**Comment by guari** [comment]
No details/screeshots/logs of the issue -> no solutions ;)

**Comment by danigonlinea** [comment]
Plugin added without any error or any warnings on LogCat or Console. I don't see any error anyway.
Here some screenshots of ADT. Of course, I restarted ADT Bundle to take full effects but you will see the results.
Tell me if you need some more details of something.
![java code](https://f.cloud.github.com/assets/1208620/2042677/69e7f246-89d4-11e3-8ff3-751ed26fedde.png)
![xml code](https://f.cloud.github.com/assets/1208620/2042681/6f391d10-89d4-11e3-9ae6-41a25cd90250.png)
![selecting moonrise](https://f.cloud.github.com/assets/1208620/2042688/791bbe28-89d4-11e3-8f44-5715eabed788.png)

**Comment by guari** [comment]
Ok.. for all the things related to text/code highlighting, download and import the .epf file linked in the Readme (https://github.com/guari/eclipse-ui-theme#syntax-highlighting-scheme).

For the white on black lines in Project Explorer it's probably because you are 'sharing' those directories and Eclipse highlight them in that way (now I don't remember if those highlighting colors are hard-coded or not..). All the other widgets/elements that I see like the blueish background in the perspective button or the scrollbar/table header or the black text for the checkboxes are forced by the OS.

Unfortunately, I have not tested yet the plugin on Windows 8 (only Win7/Vista), so if you notices something wrong that can be corrected let me know.. ;)

**Comment by guari** [comment]
It seems that in your screenshot the inner tabs of ADT are not displayed... this is an Eclipse bug that probably can be avoided in Moonrise plugin configuration with a dedicated stylesheet.
Are you experiencing the same bug with other Eclipse pre-installed themes?

**Comment by danigonlinea** [comment]
Hi again,

I was trying what you said and after import .epf file it is perfect on the code window ( Java code and XML code).
![captura de pantalla 7](https://f.cloud.github.com/assets/1208620/2059242/2517a24c-8ba0-11e3-8645-cbc18397764a.png)
And you are right in the package explorer view. In this view, it is forced by OS so ... I could change it to another theme like this:
![captura de pantalla 9](https://f.cloud.github.com/assets/1208620/2059247/5cf79c58-8ba0-11e3-8dc3-4993279d92b5.png)
But how can I change the grey background on LogCat view? It is an Eclipse preference option or it is a topic with Moonrise? I think if I can change it, I could be finally satisfy.
![captura de pantalla 8](https://f.cloud.github.com/assets/1208620/2059253/a1a49d42-8ba0-11e3-9ea6-dbdf0f50879a.png)
With pre-installed themes I had not any problem... I have to say no dark themes preinstalled. I installed Eclipse Color Theme plugin ( that have dark themes) but it only changes code view, not Package Explorer or Logcat view.

If you need more information, just say it. 
Thank you for your time.

**Comment by guari** [comment]
Remember also to download again the updated version of the .epf file ;)
