### ISSUE TITLE
Desktop Theme

### ISSUE THREAD

**Issue by amishMan91** [guari/eclipse-ui-theme#4]
Hey 
I am using your eclipse-ui-them but it doesn't look like  your pictures and i think it is because i am not using the same desktop theme like you do. Could you tell me which theme you are using.
Thanks

**Comment by guari** [comment]
Hi, if you're referring to the Ubuntu screenshot, if I remember right I caught it with the default theme (`Ambiance`) or with an other very similar called `Crunchy-orange`, but I tested it with other system themes and they gave the same result. Anyway this Eclipse theme should be quite independent from system theme. What is wrong on your machine?

**Comment by amishMan91** [comment]
oky thanks for the quick replay.
I am using a dark theme right now. My problem is that my Project Explorer box on the left side has a black background color and it seams that i can't find the preferences to change it to the same color as the rest

**Comment by guari** [comment]
I've done a quick test with a third party light theme on Ubuntu, the problem seems related to the `Tree` widget that with some particoular system themes ignores Eclipse theme setting. I'm quite sure it's a problem on the side of SWT-CSS engine and/or a particoular setting placed in that system theme for `Tree` elements. I suppose you have the same behavior for any `Tree` element in Eclipse GUI like eg. the menu on the left in Preferences dialog. 
For example, with the light ubuntu theme `Radiance` it's ok. 
Am I right?

**Comment by amishMan91** [comment]
Oky thanks i changed it to a different theme and now it works thanks again.
